### PR TITLE
fix only httpget profiling

### PR DESCRIPTION
**Pull request by phoenix-chen-2016**
修正只有HttpGet被錄下來

### CODE REVIEW

**Comment by teddymacn** [comment]
hi, can you explain more about the issue you try to fix? The place you try to modify doesn't mean it only profile GET requests, it just means when visiting the "profiling result" page, it only supports GET, which is as expected. So I'm confused why you need to change it. BTW, can you fix the line endings in your commit? You have different line ending settings which causes the pull request code cannot be compared in the github diff UI at all now.

**Comment by phoenix-chen-2016** [comment]
Can you read Chinese?

if api HttpMethod is not GET, can't profiling
current only GET api profiling

**Review by teddymacn — APPROVED** [review]
Looks correct to me, merged.

**Comment by teddymacn** [comment]
Hi Phoenix,

Yes, you are right. I reproduce the same issue. Your fix should be correct. BTW, I can read Chinese.

**Comment by teddymacn** [comment]
Released new version v1.1.4 to nuget.org with this fix.

**Comment by phoenix-chen-2016** [comment]
謝謝您^^

**Pull request merged**
